name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test default scheme using iPhone 13 simulator
    runs-on: macos-latest

    steps:
      - name: Force XCode 13.3.1
        run: sudo xcode-select -switch /Applications/Xcode_13.3.1.app
      - name: Testing Swift package
        run: exec ./.github/scripts/test_swift_package.sh
      - name: Testing iOS app
        run: xcodebuild -project SwiftCafe.xcodeproj \
            -scheme SwiftCafe \
            -destination platform=iOS\ Simulator,OS=15.4,name=iPhone\ 13 \
            clean test | xcpretty
        
     
