name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test default scheme using iPhone 13 simulator
    runs-on: macos-latest

    steps:
      - name: Testing iOS app
        run: xcodebuild -project SwiftCafe.xcodeproj -scheme SwiftCafe -destination platform=iOS\ Simulator,OS=15.4,name=iPhone\ 13 clean test | xcpretty
        
     
